spring:
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=VALUE
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 3
  h2:
    console:
      enabled: false  # Desativa o console web do H2 em produção

server:
  forward-headers-strategy: native

user-credentials:
  name: ${USERNAME:persapiens}
  password: ${PASSWORD:account}
  authorities: ROLE_USER
