spring:
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:postgresdb}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 2
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

server:
  forward-headers-strategy: native

account:
  user-credentials:
    name: ${USERNAME:persapiens}
    password: ${PASSWORD:account}
    authorities: ROLE_USER
  jwt:
    secret-key: ${JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    # 1h in millisecond
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:*}
