spring:
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=VALUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 3

server:
  forward-headers-strategy: native

user-credentials:
  name: ${USERNAME:persapiens}
  password: ${PASSWORD:account}
  authorities: ROLE_USER
