create sequence seq_credit_account start with 1 increment by 1;
create sequence seq_credit_category start with 1 increment by 1;
create sequence seq_credit_entry start with 1 increment by 1;
create sequence seq_debit_account start with 1 increment by 1;
create sequence seq_debit_category start with 1 increment by 1;
create sequence seq_debit_entry start with 1 increment by 1;
create sequence seq_equity_account start with 1 increment by 1;
create sequence seq_equity_category start with 1 increment by 1;
create sequence seq_owner start with 1 increment by 1;
create sequence seq_transfer_entry start with 1 increment by 1;
create table credit_account (category_id bigint not null, id bigint not null, description varchar(255) not null unique, primary key (id));
create table credit_category (id bigint not null, description varchar(255) not null unique, primary key (id));
create table credit_entry (value numeric(38,2) not null, date timestamp(6) not null, id bigint not null, in_account_id bigint not null, in_owner_id bigint not null, out_account_id bigint not null, out_owner_id bigint not null, note varchar(255), primary key (id));
create table debit_account (category_id bigint not null, id bigint not null, description varchar(255) not null unique, primary key (id));
create table debit_category (id bigint not null, description varchar(255) not null unique, primary key (id));
create table debit_entry (value numeric(38,2) not null, date timestamp(6) not null, id bigint not null, in_account_id bigint not null, in_owner_id bigint not null, out_account_id bigint not null, out_owner_id bigint not null, note varchar(255), primary key (id));
create table equity_account (category_id bigint not null, id bigint not null, description varchar(255) not null unique, primary key (id));
create table equity_category (id bigint not null, description varchar(255) not null unique, primary key (id));
create table owner (id bigint not null, name varchar(255) not null unique, primary key (id));
create table owner_equity_account_initial_value (value numeric(38,2) not null, equity_account_id bigint not null, owner_id bigint not null, primary key (equity_account_id, owner_id));
create table transfer_entry (value numeric(38,2) not null, date timestamp(6) not null, id bigint not null, in_account_id bigint not null, in_owner_id bigint not null, out_account_id bigint not null, out_owner_id bigint not null, note varchar(255), primary key (id));
alter table if exists credit_account add constraint fk_creditAccount_category foreign key (category_id) references credit_category;
alter table if exists credit_entry add constraint FK2hy0du2iluqr6lys5ynxgjp3o foreign key (in_owner_id) references owner;
alter table if exists credit_entry add constraint FKpvdm9aqk7v8nyoqoho4nnsrav foreign key (out_owner_id) references owner;
alter table if exists credit_entry add constraint fk_creditEntry_inAccount foreign key (in_account_id) references equity_account;
alter table if exists credit_entry add constraint fk_creditEntry_outAccount foreign key (out_account_id) references credit_account;
alter table if exists debit_account add constraint fk_debitAccount_category foreign key (category_id) references debit_category;
alter table if exists debit_entry add constraint FKd4s5bwc3opwoqhhmntlbg0s7b foreign key (in_owner_id) references owner;
alter table if exists debit_entry add constraint FK7ghomlwyt1l6jax5gw4nelfky foreign key (out_owner_id) references owner;
alter table if exists debit_entry add constraint fk_debitEntry_inAccount foreign key (in_account_id) references debit_account;
alter table if exists debit_entry add constraint fk_debitEntry_outAccount foreign key (out_account_id) references equity_account;
alter table if exists equity_account add constraint fk_equityAccount_category foreign key (category_id) references equity_category;
alter table if exists owner_equity_account_initial_value add constraint fk_ownerEquityAccountInitialValue_equityAccount foreign key (equity_account_id) references equity_account;
alter table if exists owner_equity_account_initial_value add constraint fk_ownerEquityAccountInitialValue_owner foreign key (owner_id) references owner;
alter table if exists transfer_entry add constraint FKrbeielpge1qmgohy9h1qxh0b5 foreign key (in_owner_id) references owner;
alter table if exists transfer_entry add constraint FKa2bcx21viqmptmgdtwo3t00vy foreign key (out_owner_id) references owner;
alter table if exists transfer_entry add constraint fk_transferEntry_inAccount foreign key (in_account_id) references equity_account;
alter table if exists transfer_entry add constraint fk_transferEntry_outAccount foreign key (out_account_id) references equity_account;
