name: GraalVM CI

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: GraalVM Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [21]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up GraalVM ${{ matrix.java }} 
        uses: graalvm/setup-graalvm@v1.3.3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache local Maven repository
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-graavm-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-graavm-

      - name: Validate
        run: ./mvnw -B clean validate

      - name: Native App build
        run: ./mvnw -B -Pnative -DskipTests=true native:compile

      - name: Native app upload artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: native
          path: |
            target/account-backend*

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
        if: ${{ vars.DEPLOY =='true' && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'persapiens-classes/account-backend' }}

      - name: Zip, copy and deploy executable via SSH
        run: |
          zip -j target/account-backend.zip target/account-backend
          scp -i ~/.ssh/id_rsa -P ${{ secrets.DEPLOY_PORT }} target/account-backend.zip ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "~/deploy.sh"
        if: ${{ vars.DEPLOY =='true' && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'persapiens-classes/account-backend' }}
        
      - name: Native Image build
        run: ./mvnw -B -Pnative -DskipTests=true spring-boot:build-image

      - name: Docker Hub login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'persapiens-classes/account-backend' }}

      - name: Create tag
        run: docker tag account-backend:1.0.0-SNAPSHOT persapiens/account-backend:native
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'persapiens-classes/account-backend' }}

      - name: Push image
        run: docker push persapiens/account-backend:native
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'persapiens-classes/account-backend' }}
